# Generated by Django 3.2 on 2021-04-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
