# Generated by Django 3.2 on 2021-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='price',
            field=models.CharField(max_length=1000),
        ),
    ]
